-- Create the meal_calendars table
CREATE TABLE meal_calendars (
    id INT PRIMARY KEY,
    term_name TEXT,
    semester_start TIMESTAMPTZ,
    rotation_length_weeks INT,
    is_active BOOLEAN
);

-- Create the academic_breaks table
CREATE TABLE academic_breaks (
    id INT PRIMARY KEY,
    calendar_id INT,
    name TEXT,
    start_date TIMESTAMPTZ,
    end_date TIMESTAMPTZ,
    rotation_skip_days INT,
    FOREIGN KEY (calendar_id) REFERENCES meal_calendars(id)
);

-- Create the meals table
CREATE TABLE meals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day TEXT,
    week_number BIGINT,
    meal_type TEXT,
    dish_name TEXT
);
