-- Create the feedback table
CREATE TABLE IF NOT EXISTS feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT,
    user_name TEXT,
    content TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
