services:
  - type: web
    name: kss-discord-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: FALSE
      - key: GUILD_ID
        sync: FALSE
      - key: HEALTHCHECK_URL
        sync: FALSE
      - key: SUPABASE_URL
        sync: FALSE
      - key: SUPABASE_DB_URL
        sync: FALSE
      - key: SUPABASE_SERVICE_KEY
        sync: FALSE
